### ISSUE TITLE
Just a comment

### ISSUE THREAD

**Issue by zoffixznet** [JJ/perl6em#5]
Hey. Someone dropped a link to https://jj.github.io/perl6em/perl6.html#org2bfd54e on IRC.

Just wanted to mention that description of `».` probably should mention that it's an autothreaded operator and any sideffects such a call produces would have all of the issues related to threads (data races if used unsafely, side effects produced out of order, etc).

The actual autothreading is not yet implemented, so you won't spot those issues right now; but once it is, you will, and we try to make that point clear, so fewer people's code breaks when we do make it work (I heard dates named for the implementation to be some time in 2018, but you know how predictions are...)

**Comment by JJ** [comment]
Well, this is intended as a basic manual for those who don't even know how to program, as in their first contact with a programming language. Mentioning threads when I have not even introduced variables might be a bit strong... Besides, that is something that I didn't know, personally. 
I am not sure I will even mention threads. If I find a way to segue naturally from the rest of the book, maybe. If I manage to understand them, of course. I'll check out IRC to see if there was some other comment. Thanks!

**Comment by zoffixznet** [comment]
Then a `.map` is a better alternative to  `».`

**Comment by JJ** [comment]
I wanted to leave map for later on, when blocks have actually been
introduced... Do you think it would go better right here? Chapter is about
Bool types, mainly.

**Comment by zoffixznet** [comment]
Then just leave out `».`

Right now you're showing all of your readers how to introduce hard-to-find bugs into their code, because you're purposely leaving out the most crucial piece of information about the operator.

**Comment by JJ** [comment]
OK, will bear that in mind. Will include a note or something. Thanks for the feedback.
